config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :posts do
    resources :comments
  end
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  root to: "users#new"

  get '/:username', to: 'profiles#show', as: :profile
  get '/:username/edit', to: 'profiles#edit', as: :edit_profile
  # post ':username', to: 'profiles#update'
  patch '/:username', to: 'profiles#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :caption, presence: true
  validates :user_id, presence: true
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 4, maximum: 16}
  validates :username, uniqueness: true
  has_many :posts, dependent: :destroy
  has_one_attached :avatar
  has_secure_password
  has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :is_loggedin?, :current_user

  def current_user
    #check session user and set to instance variable to use other in controllers
    if session[:user_id]
    @user = User.find(session[:user_id])
    end
  end

  def is_loggedin?
    !!current_user
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      #we must change route this is for testing
      redirect_to profile_path(current_user.username)
    else
      render post_path(@post)
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to posts_path
  end


  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorized, except: [:index, :new, :create]


  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "That is a nice looking picture!"
      redirect_to profile_path(current_user.username)
    else
      flash.now[:alert] = "Your new post was not processed!"
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post Updated"
    redirect_to post_path(@post)
    else
      flash[:alert] = "Update failed. Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:caption, :image, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def authorized
    redirect_to login_path unless session[:user_id]
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :my_profile, only: [:edit, :update]

  def show
    @user = User.find_by(username: params[:username])
    @posts = User.find_by(username: params[:username]).posts
  end

  def edit
    @user = User.find_by(username: params[:username])
  end

  def update
    @user = User.find_by(username: params[:username])
    if @user.update(profile_params)
      redirect_to profile_path(@user.username)
    else
      render :edit
    end
  end


  private

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def my_profile
    @user = User.find_by(username: params[:username])
    unless current_user == @user
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :authorized, except: [:show, :new, :create]

  def new
  end

  def create
    # Find the user
    @user = User.find_by(username: params[:username])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      # We want to show all of the post that are tied to this user
      redirect_to profile_path(@user.username)
    else
      flash[:alert] = "Username or Password incorrect!"
      redirect_to login_path
    end
  end

  def show

  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end

private
  def authorized
    redirect_to login_path unless session[:user_id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorized, except: [:index, :new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to edit_profile_path(@user.username)
    else
      flash[:alert] = "Username must be atleast 4 characters, no more than 16 characters!"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end




private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def authorized
    redirect_to login_path unless session[:user_id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_for(flash_type)
  { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
  end


  def profile_avatar(user)
    @user = User.find(session[:user_id])
    if user.avatar.attachment.present?
      image_tag user.avatar.variant(resize: "150x150")
    else
      image_tag 'default-avatar.png'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <a class="navbar-brand">
    <h2><%= link_to "HanzAgram", posts_path %></h2>
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">

      <% if session[:user_id] %>

        <li class="nav-item">
          <a class="nav-link"><%= link_to "New Post", new_post_path%></a>
        </li>

        <li class="nav-item">
          <a class="nav-link"><%= link_to 'My Profile', profile_path(current_user.username) %></a>
        </li>

        <li class="nav-item">
          <a class="nav-link"><%= link_to 'Edit Profile', edit_profile_path(current_user.username) %></a>
        <li>

        <li class="nav-item">
          <%= form_tag "/logout", method: :delete do %>
            <a class="nav-link"><%= submit_tag "Logout", class: 'btn' %></a>
          <% end %>
        </li>

      <% else %>

        <li class="nav-item">
          <a class="nav-link"><%= link_to "Log In", login_path %></a>
        </li>

         <li class="nav-item">
           <a class="nav-link"><%= link_to "Sign Up", new_user_path %></a>
         </li>

       <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hanzagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
      <% end %>
    </div>
    <% if (params[:controller]  != "users") && params[:action] != "new" %>
      <%= render 'layouts/navbar' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<% @posts.each do |post| %>

  <h3><%= post.user.username %></h3><br/>

  <%= link_to (image_tag post.image), post_path(post) %><br/>

  <%= post.caption %><br>
  <% if post.comments %>
    <% post.comments.each do |comment| %>
      <%= comment.user.username %>
      <%= comment.content %>
      <% if comment.user == current_user %>
        <%= link_to (post_comment_path(post, comment)), method: :delete, data: {confirm: "Really? Really? Really? Okay " } %>
      <% end %>
    <% end %>

    <%= form_for [post, post.comments.new] do |f| %>
      <%= f.text_field :content, placeholder: 'Add a comment...' %>
    <% end %>
  <% end %>
  <br/>

<% end %>

app/views/posts/_posts.html.erb
<div class="post-list">

  <!-- POST CARD -->
  <% @posts.reverse.each do |post| %>
  <div class="post-item">
    <div class="post-content thumbnail">
      <%= link_to post.user.username, profile_path(post.user.username) %>
      <br/>

      <%= link_to (image_tag post.image.variant(resize: "350x350"), class: 'post-image'), post_path(post) %>
      <p class="image-caption"><%= post.caption %></p>
    </div>

    <!-- COMMENT SECTION -->
    <div class="comment-section">
      <div class="comment-list">
        <% if post.comments %>
          <% post.comments.each do |comment| %>
            <div class="comment-item">
              <blockquote class="blockquote">
                <p class="comment-text"><%= comment.content %></p>
                <footer class="blockquote-footer"><%= comment.user.username %></footer>
              </blockquote>
              <% if comment.user == current_user %>
                <%= link_to 'delete', post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, class: 'text-danger btn' %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="post-comment-form">
        <%= form_for [post, post.comments.new] do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...' %>
        <% end %>
      </div>
    </div>
    <!-- COMMENT SECTION -->
  </div>

  <% end %>
  <!-- POST CARD -->
</div>

app/views/posts/edit.html.erb
<h2>Edit your Picture!</h2>

<%= image_tag @post.image %>
<%= form_for @post do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image%>
  <br/>
  <%= f.label :caption %>
  <%= f.text_field :caption %>
  <br/>
  <%= f.submit "Upload!"%>
<% end %>

<%= form_tag post_path(@post), method: 'delete' do %>
  <% submit_tag 'Delete Post'%>
<% end %>

app/views/posts/index.html.erb
<%=render "posts"  %>

app/views/posts/new.html.erb
<div class="new-post-background"></div>

<div class="registration-bg">

  <div class="container">

    <div class="row">

      <div class="col-md-12">

        <div class="log-in panel">

          <div class="panel-heading">

            <h2 id="upload-pic-h2">Upload Your Post</h2>

          </div>

          <%= form_for(@post) do |f| %>

            <div class="panel-body">
              <div class="input-lg" id="new-post-image"><%= f.label :image %></div>
              <div class="input-lg"><%= f.file_field :image %></div>

              <div class="input-lg" id="new-post-caption"><%= f.label :caption %></div>
              <div class="input-lg"><%= f.text_field :caption %></div>

              <div class="btn-sm"><%= f.submit "Upload!" %></div>

            </div>

          <% end %>

      </div>

    </div>

  </div>

</div>

</div>

app/views/posts/show.html.erb
<%= link_to (image_tag @post.image), post_path(@post) %>
<br/ >

app/views/profiles/edit.html.erb
<div class="container">

  <div class="row">

    <div class="col-md-12 text-center">

      <h1>Edit Profile</h1>

      <h4>Change your profile image:</h4>

      

    </div>

    <div class="col-md-12 text-center"><%= profile_avatar(@user) %></div>

    <div class="col-md-12 text-center">

      <%= form_for @user, url: "/#{@user.username}", method: :patch do |f| %>

      <div class="panel-body">

        <div class="btn-sm"><%= f.file_field :avatar%></div>

        <h4>Update your bio:</h4>

        <div class="input-lg"><%= f.text_area :bio, rows: 4 %></div>

        <%= f.submit "Update Profile", :class => 'btn btn-primary' %>

        <% end %>

      </div>

    </div>

  </div>

</div>

app/views/profiles/show.html.erb
<style>
.show-style {
  width: 100%;
  max-width: 800px;
  padding: 15px;
  margin: auto;
}
 </style>

 <% if current_user == @user %>
   <div class="container">
     <%= profile_avatar(@user) %>
     <h3 class="profile-user-name">
      <%= @user.username %>
     <br>
     <h3>Bio:</h3>
     <i><%= @user.bio %></i>
     <br>
     <%= pluralize @user.posts.count, 'post' %>
   </div>
 <% end %>

<hr>
<%= render "posts/posts"%>

app/views/users/new.html.erb
<div class="sign-up-background"></div>

<div class="registration-bg">

  <div class="container">

    <div class="row">

      <div class="col-md-12">

        <div class="log-in panel">

          <div class="panel-heading">

            <h2 id="sign-up-h2">Create Your Account</h2>

          </div>

          <%= form_for(@user) do |f| %>

            <div class="panel-body">
              <div class="input-lg" id="sign-up-username"><%= f.label :username %></div>
              <div class="input-lg"><%= f.text_field :username %></div>

              <div class="input-lg" id="sign-up-password"><%= f.label :password %></div>
              <div class="input-lg"><%= f.password_field :password %></div>

              <div class="btn-sm"><%= f.submit "Sign Up!" %></div>
              <div class="btn-sm"> <%= f.button link_to "Log In", login_path %></div>

            </div>

          <% end %>

      </div>

    </div>

  </div>

</div>

</div>

app/views/users/show.html.erb
<%= @user.username %>